title = "SOGo Installation"
description = "Installationsanweisungen SOGo Groupware Server"
author = "Stefan MÃ¼ller <s.mueller@it.kls-glt.de>"

# [output.html]
# additional-css = ["test.css"]
# additional-js = ["test.js"]
